from django.test import TestCase
from django.contrib.auth import get_user_model
from accounts.models import Token


User = get_user_model()


class UserModelTest(TestCase):

    def test_user_is_valid_with_email_only(self):
        user = User(email='test@test.test')
        user.full_clean()

    def test_email_is_primary_key(self):
        user = User(email='test@test.test')
        self.assertEqual(user.pk, 'test@test.test')


class TokenModelTest(TestCase):

    def test_links_user_with_autogenerated_uid(self):
        token1 = Token.objects.create(email='test@test.test')
        token2 = Token.objects.create(email='test@test.test')
        self.assertNotEqual(token1.uid, token2.uid)
